config/routes.rb
Rails.application.routes.draw do
  root 'pictures#index'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :pictures, only: [:index, :new, :create, :edit, :update, :destroy]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin?
      can :access, :rails_admin
      can :manage, :all
    end
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  validates :image, presence: true
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable
  mount_uploader :avatar, AvatarUploader
  has_many :pictures

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(email: auth.info.email)

    unless user
      user = User.new(
          name:     auth.extra.raw_info.name,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          image_url:   auth.info.image,
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  PERMISSIBLE_ATTRIBUTES = %i(name avatar avatar_cache)

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
      devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :find_picture, only: [:edit, :update, :destroy]

  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(pictures_params)
    @picture.user_id = current_user.id
    if @picture.save
      redirect_to root_path, notice: "共有しました！"
      NoticeMailer.sendmail_picture(@picture).deliver
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @picture.update(pictures_params)
      redirect_to root_path, notice: "更新しました！"
    else
      render :new
    end
  end

  def destroy
    @picture.destroy
    redirect_to root_path, notice: "削除しました！"
  end

  private
    def pictures_params
      params.require(:picture).permit(:image, :content)
    end

    def find_picture
      @picture = Picture.find(params[:id])
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def profile_img(user)
    return image_tag(user.avatar, alt: user.name) if user.avatar?
    unless user.provider.blank?
      img_url = user.image_url
    else
      img_url = 'no_image.png'
    end
    image_tag(img_url, alt: user.name)
  end
end

module ActionView
  module Helpers
    module FormHelper
      def error_messages!(object_name, options = {})
        resource = self.instance_variable_get("@#{object_name}")
        return '' if !resource || resource.errors.empty?

        messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

        html = <<-HTML
          <div class="alert alert-danger">
            <ul>#{messages}</ul>
          </div>
        HTML

        html.html_safe
      end

      def error_css(object_name, method, options = {})
        resource = self.instance_variable_get("@#{object_name}")
        return '' if resource.errors.empty?

        resource.errors.include?(method) ? 'has-error' : ''
      end
    end

    class FormBuilder
      def error_messages!(options = {})
        @template.error_messages!(@object_name, options.merge(object: @object))
      end

      def error_css(method, options = {})
        @template.error_css(@object_name, method, options.merge(object: @object))
      end
    end
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instagram?</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <header>
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <%= link_to "Instagram?", root_path, class: "navbar-brand" %>
            <ul class="col-xs-6 col-sm-4 nav navbar-nav head_icon">
              <li class="col-xs-4 col-sm-4"><%= link_to "", new_picture_path,
               class: 'glyphicon glyphicon-camera' %></li>

              <% if user_signed_in? %>
                <li class="col-xs-4 col-sm-4"><%= link_to "", edit_user_registration_path,
                 class: 'glyphicon glyphicon-user' %></li>
                <li class="col-xs-4 col-sm-4"><%= link_to "", destroy_user_session_path,
                 class: 'glyphicon glyphicon-log-out', method: :delete %></li>
              <% else %>
                <li class="col-xs-4 col-sm-4"><%= link_to "", new_user_session_path,
                 class: 'glyphicon glyphicon-log-in' %></li>
                <li class="col-xs-4 col-sm-4"><%= link_to "", new_user_registration_path,
                 class: 'glyphicon glyphicon-pencil' %></li>
              <% end %>
            </ul>
          </div>
      </header>
    </div>
  </div>

<%= yield %>

</body>
</html>

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <%= f.error_messages! %>

  <%= f.label      :image %>
  <%= f.file_field :image, class: 'form-control' %>
  <br>
  <%= f.label      :content %>
  <%= f.text_field :content, class: 'form-control' %>
  <br>
  <%= f.submit '共有', class: 'btn btn-primary btn-block' %>
<% end %>

<%= link_to "一覧に戻る", root_path %>

app/views/pictures/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>投稿を編集する</h3>

    <%= render 'form' %>

  </div>
</div>

app/views/pictures/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <section class="main-header">
      <p class="flash"><%= notice %><%= alert %></p>
    </section>
    <h1>Pictures</h1>

    <% @pictures.each do |picture| %>
      <div class = "row">
        <p class="prof_img"><%= profile_img(picture.user) if profile_img(picture.user) %></p>
        <p class="user_name"><%= picture.user.name %></p>

        <% if picture.user == current_user %>
          <%= link_to "削除", picture_path(picture.id), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'index_btn btn btn-default btn-sm btn btn-danger' %>
          <%= link_to "編集", edit_picture_path(picture.id), class: 'index_btn btn btn-default btn-sm btn-success' %>
        <% end %>

        <div class="clear">
          <%= image_tag(picture.image) %></br>
          <%= picture.content %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pictures/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>写真を共有する</h3>

    <%= render 'form' %>

  </div>
</div>